version: "3.9"
services:
  frigate:
    container_name: frigate-l4t-ml
    #image: blakeblackshear/frigate:0.11.1
    #image: frigate_frigate
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    privileged: true
    shm_size: "256mb"
    runtime: "nvidia"
    devices:
      - "/dev/nvhost-ctrl:/dev/nvhost-ctrl"
      - "/dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu"
      - "/dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu"
      - "/dev/nvmap:/dev/nvmap"
      - "/dev/nvhost-gpu:/dev/nvhost-gpu"
      - "/dev/nvhost-as-gpu:/dev/nvhost-as-gpu"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- .:/lab/frigate:cached
      - ./config/config.yml:/config/config.yml:ro
      #- ./debug:/media/frigate
      #- /dev/bus/usb:/dev/bus/usb
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      #- /mnt/ssd1/julian_dev/frigate/config/config.yml:/config/config.yml:ro
      - /mnt/dev/frigate/v0.11.1/debug:/media/frigate
      - /mnt/dev/frigate/v0.11.1/frigate:/opt/frigate/frigate
    ports:
      - "1935:1935"
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "8080:8080"
      # - "11883:11883"
    # entrypoint: ["sudo", "/init"]
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      # - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    # deploy:
    #   resources:
    #     limits:
    #       memory: 40G
    #     reservations:
    #       memory: 5G
    #       devices:
    #       - driver: nvidia
    #         capabilities: [gpu]
